from sqlalchemy import Column, MetaData, Table, Uuid
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    """Shared (public schema) models: organizations, users, refresh_tokens, pipeline_stages."""


class TenantBase(DeclarativeBase):
    """Per-tenant schema models. The literal schema name 'tenant' in each
    model's __table_args__ is replaced at query time via SQLAlchemy's
    schema_translate_map execution option set on the connection.

    The metadata carries a default schema of 'tenant' so that unqualified
    ForeignKey strings between tenant tables (e.g. ForeignKey("customers.id"))
    resolve to the schema-qualified table key 'tenant.customers'. Without this,
    mapper configuration fails with NoReferencedTableError the first time a
    tenant model is queried, because the table is registered as 'tenant.<name>'
    while the FK looks up the bare '<name>'."""

    metadata = MetaData(schema="tenant")


# Tenant tables carry cross-schema FKs to public.users (created_by_id,
# updated_by_id, deleted_by_id, assigned_to_id, ...). The real User model lives
# in Base.metadata, so those "public.users.id" FK strings cannot be resolved
# inside TenantBase.metadata — and every INSERT into a tenant table then raises
# NoReferencedTableError during the flush dependency sort. Register a minimal
# stub of public.users here so the FK target resolves at the ORM layer. The
# actual users table + FK constraints are created by the migrations; this stub
# is ORM-resolution-only (create_all uses checkfirst, so it never recreates the
# real public.users, and tenant migrations are hand-written, not autogenerated).
Table(
    "users",
    TenantBase.metadata,
    Column("id", Uuid, primary_key=True),
    schema="public",
)
